$(document).ready(function(){
  $('.headingsInSecond').hide();
  $('.bottomTexts').hide();
  $('.matrix-container').hide();
  $('.table-container-references').hide();
  $("#appButton").click(function(){
    $('.bottomTexts').hide();
    $('.matrix-container').hide();
    $('.table-container-references').hide();
    $('#firstText').slideToggle();
  });
  $("#algButton").click(function(){
    $('.bottomTexts').hide();
    $('.matrix-container').hide();
    $('.table-container-references').hide();
    $('#secondText').slideToggle();
    $('.matrix-container').slideToggle();
    $('#tempText').slideToggle();
  });
  $("#inspButton").click(function(){
    $('.bottomTexts').hide();
    $('.matrix-container').hide();
    $('.table-container-references').hide();
    $('#thirdText').slideToggle();
  });
  $("#refButton").click(function(){
    $('.bottomTexts').hide();
    $('.matrix-container').hide();
    $('.table-container-references').hide();
    $('#fourthText').slideToggle();
    $('.table-container-references').slideToggle();
  });
});
